language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t cybe4punk/legendary-disco -f Dockefile.dev .

script:
    - docker run -e CI=true cybe4punk/legendary-disco npm run test -- --coverage